version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: music-licensing-db
    environment:
      POSTGRES_DB: music_licensing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - music-licensing-network

  redis:
    image: redis:7-alpine
    container_name: music-licensing-redis
    ports:
      - "6379:6379"
    networks:
      - music-licensing-network

  adminer:
    image: adminer:4.8.1
    container_name: music-licensing-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - music-licensing-network

  # Backend runs locally, not in Docker
  

volumes:
  postgres_data:

networks:
  music-licensing-network:
    driver: bridge